export const ipcChannels = {
  getStatus: "zenx:app-server:get-status",
  getPendingApprovals: "zenx:protocol:get-pending-approvals",
  request: "zenx:protocol:request",
  approvalRequest: "zenx:protocol:approval-request",
  approvalResolved: "zenx:protocol:approval-resolved",
  respondApproval: "zenx:protocol:respond-approval",
  status: "zenx:app-server:status",
  notification: "zenx:protocol:notification",
  settingsGet: "zenx:settings:get",
  settingsSave: "zenx:settings:save",
  subscriptionLogin: "zenx:settings:subscription-login",
  subscriptionManualCode: "zenx:settings:subscription-manual-code",
  subscriptionManualRequested: "zenx:settings:subscription-manual-requested",
  subscriptionLogout: "zenx:settings:subscription-logout",
  triggersGet: "zenx:triggers:get",
  triggersCreate: "zenx:triggers:create",
  triggersCancel: "zenx:triggers:cancel",
  triggersSignal: "zenx:triggers:signal",
  triggersChanged: "zenx:triggers:changed",
  roomsCreate: "zenx:rooms:create",
  roomsAddMember: "zenx:rooms:add-member",
  roomsRemoveMember: "zenx:rooms:remove-member",
  roomsPost: "zenx:rooms:post",
} as const;
